{
  "openapi": "3.0.0",
  "info": {
    "title": "Deribit API - Session Management",
    "version": "2.1.1",
    "description": "Deribit API specification for Session Management endpoints"
  },
  "servers": [
    {
      "url": "http://localhost:8082/api/v2",
      "description": "local test server"
    },
    {
      "url": "https://test.deribit.com/api/v2"
    }
  ],
  "tags": [
    {
      "name": "Session Management"
    }
  ],
  "paths": {
    "/public/set_heartbeat": {
      "get": {
        "parameters": [
          {
            "description": "The heartbeat interval in seconds, but not less than 10",
            "in": "query",
            "name": "interval",
            "required": true,
            "schema": {
              "example": 30,
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/OkResponse",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "description": "Response example",
                    "value": {
                      "jsonrpc": "2.0",
                      "id": 9098,
                      "result": "ok"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Signals the Websocket connection to send and request heartbeats. Heartbeats can be used to detect stale connections. When heartbeats have been set up, the API server will send `heartbeat` messages and `test_request` messages. Your software should respond to `test_request` messages by sending a `/api/v2/public/test` request. If your software fails to do so, the API server will immediately close the connection. If your account is configured to cancel on disconnect, any orders opened over the connection will be cancelled.",
        "tags": [
          "Session Management",
          "Public",
          "WebSocket Only"
        ],
        "requestBody": {
          "description": "JSON-RPC request body",
          "content": {
            "application/json": {
              "examples": {
                "request": {
                  "description": "JSON-RPC Request Example",
                  "value": {
                    "jsonrpc": "2.0",
                    "id": 9098,
                    "method": "public/set_heartbeat",
                    "params": {
                      "interval": 30
                    }
                  }
                }
              }
            }
          }
        },
        "x-mint": {
          "metadata": {
            "title": "public/set_heartbeat",
            "og:title": "public/set_heartbeat"
          },
          "href": "/api-reference/session-management/public-set_heartbeat"
        }
      }
    },
    "/public/disable_heartbeat": {
      "get": {
        "description": "Stop sending heartbeat messages.",
        "tags": [
          "Session Management",
          "WebSocket Only",
          "Public"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/OkResponse",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "description": "Response example",
                    "value": {
                      "jsonrpc": "2.0",
                      "id": 3562,
                      "result": "ok"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorMessageResponse"
          }
        },
        "requestBody": {
          "description": "JSON-RPC request body",
          "content": {
            "application/json": {
              "examples": {
                "request": {
                  "description": "JSON-RPC Request Example",
                  "value": {
                    "jsonrpc": "2.0",
                    "id": 3562,
                    "method": "public/disable_heartbeat",
                    "params": {}
                  }
                }
              }
            }
          }
        },
        "x-mint": {
          "metadata": {
            "title": "public/disable_heartbeat",
            "og:title": "public/disable_heartbeat"
          },
          "href": "/api-reference/session-management/public-disable_heartbeat"
        }
      }
    },
    "/private/enable_cancel_on_disconnect": {
      "get": {
        "description": "Enable Cancel On Disconnect for the connection. After enabling, all orders created via this connection will be automatically cancelled when the connection is closed. Cancel is triggered in the following cases: when the TCP connection is properly terminated, when the connection is closed due to 10 minutes of inactivity, or when a heartbeat detects a disconnection. To reduce the inactivity timeout, consider using [public/set_heartbeat](https://docs.deribit.com/#public-set_heartbeat). **Note**: If the connection is gracefully closed using [private/logout](https://docs.deribit.com/#private-logout), cancel-on-disconnect will **not** be triggered. **Notice**: Cancel-on-Disconnect does not affect orders created by other connections - they will remain active! When change is applied on the `account` scope, then every newly opened connection will start with **active** Cancel on Disconnect.",
        "tags": [
          "Session Management",
          "Private"
        ],
        "parameters": [
          {
            "name": "scope",
            "description": "Specifies if Cancel On Disconnect change should be applied/checked for the current connection or the account (default - `connection`) **NOTICE:** Scope `connection` can be used only when working via Websocket.",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "connection",
                "account"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/OkResponse",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "description": "Response example",
                    "value": {
                      "jsonrpc": "2.0",
                      "id": 7859,
                      "result": "ok"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorMessageResponse"
          }
        },
        "requestBody": {
          "description": "JSON-RPC request body",
          "content": {
            "application/json": {
              "examples": {
                "request": {
                  "description": "JSON-RPC Request Example",
                  "value": {
                    "jsonrpc": "2.0",
                    "id": 7859,
                    "method": "private/enable_cancel_on_disconnect",
                    "params": {
                      "scope": "account"
                    }
                  }
                }
              }
            }
          }
        },
        "x-mint": {
          "metadata": {
            "title": "private/enable_cancel_on_disconnect",
            "og:title": "private/enable_cancel_on_disconnect"
          },
          "href": "/api-reference/session-management/private-enable_cancel_on_disconnect"
        }
      }
    },
    "/private/disable_cancel_on_disconnect": {
      "get": {
        "description": "Disable Cancel On Disconnect for the connection. When change is applied for the account, then every newly opened connection will start with **inactive** Cancel on Disconnect.",
        "tags": [
          "Session Management",
          "Private"
        ],
        "parameters": [
          {
            "name": "scope",
            "description": "Specifies if Cancel On Disconnect change should be applied/checked for the current connection or the account (default - `connection`) **NOTICE:** Scope `connection` can be used only when working via Websocket.",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "connection",
                "account"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/OkResponse",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "description": "Response example",
                    "value": {
                      "jsonrpc": "2.0",
                      "id": 1569,
                      "result": "ok"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorMessageResponse"
          }
        },
        "requestBody": {
          "description": "JSON-RPC request body",
          "content": {
            "application/json": {
              "examples": {
                "request": {
                  "description": "JSON-RPC Request Example",
                  "value": {
                    "jsonrpc": "2.0",
                    "id": 1569,
                    "method": "private/disable_cancel_on_disconnect",
                    "params": {
                      "scope": "account"
                    }
                  }
                }
              }
            }
          }
        },
        "x-mint": {
          "metadata": {
            "title": "private/disable_cancel_on_disconnect",
            "og:title": "private/disable_cancel_on_disconnect"
          },
          "href": "/api-reference/session-management/private-disable_cancel_on_disconnect"
        }
      }
    },
    "/private/get_cancel_on_disconnect": {
      "get": {
        "description": "Read current Cancel On Disconnect configuration for the account.",
        "tags": [
          "Session Management",
          "Private"
        ],
        "parameters": [
          {
            "name": "scope",
            "description": "Specifies if Cancel On Disconnect change should be applied/checked for the current connection or the account (default - `connection`) **NOTICE:** Scope `connection` can be used only when working via Websocket.",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "connection",
                "account"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/PrivateGetCancelOnDisconnectResponse",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "description": "Response example",
                    "value": {
                      "jsonrpc": "2.0",
                      "id": 220,
                      "result": {
                        "scope": "account",
                        "enabled": false
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/ErrorMessageResponse"
          }
        },
        "requestBody": {
          "description": "JSON-RPC request body",
          "content": {
            "application/json": {
              "examples": {
                "request": {
                  "description": "JSON-RPC Request Example",
                  "value": {
                    "jsonrpc": "2.0",
                    "id": 220,
                    "method": "private/get_cancel_on_disconnect",
                    "params": {
                      "scope": "account"
                    }
                  }
                }
              }
            }
          }
        },
        "x-mint": {
          "metadata": {
            "title": "private/get_cancel_on_disconnect",
            "og:title": "private/get_cancel_on_disconnect"
          },
          "href": "/api-reference/session-management/private-get_cancel_on_disconnect"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PrivateGetCancelOnDisconnectResponse": {
        "properties": {
          "jsonrpc": {
            "description": "The JSON-RPC version (2.0)",
            "enum": [
              "2.0"
            ],
            "type": "string"
          },
          "id": {
            "description": "The id that was sent in the request",
            "type": "integer"
          },
          "result": {
            "properties": {
              "scope": {
                "$ref": "#/components/schemas/cod_scope"
              },
              "enabled": {
                "$ref": "#/components/schemas/enabled_field"
              }
            },
            "type": "object"
          }
        },
        "required": [
          "result",
          "jsonrpc"
        ],
        "type": "object"
      },
      "OkResponse": {
        "properties": {
          "jsonrpc": {
            "description": "The JSON-RPC version (2.0)",
            "enum": [
              "2.0"
            ],
            "type": "string"
          },
          "id": {
            "description": "The id that was sent in the request",
            "type": "integer"
          },
          "result": {
            "description": "Result of method execution. `ok` in case of success",
            "enum": [
              "ok"
            ],
            "type": "string"
          }
        },
        "required": [
          "result",
          "jsonrpc"
        ],
        "type": "object"
      },
      "ErrorMessageResponse": {
        "properties": {
          "jsonrpc": {
            "description": "The JSON-RPC version (2.0)",
            "enum": [
              "2.0"
            ],
            "type": "string"
          },
          "id": {
            "description": "The id that was sent in the request",
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "error": {
            "type": "integer"
          }
        },
        "required": [
          "message",
          "jsonrpc",
          "error"
        ],
        "type": "object"
      },
      "cod_scope": {
        "description": "Informs if Cancel on Disconnect was checked for the current connection or the account",
        "enum": [
          "connection",
          "account"
        ],
        "type": "string"
      },
      "enabled_field": {
        "description": "Current configuration status",
        "example": true,
        "type": "boolean"
      },
      "ErrorResponse": {
        "type": "object",
        "description": "Generic error response for broken references",
        "properties": {
          "jsonrpc": {
            "type": "string",
            "enum": [
              "2.0"
            ]
          },
          "error": {
            "type": "object",
            "properties": {
              "code": {
                "type": "integer",
                "description": "Error code"
              },
              "message": {
                "type": "string",
                "description": "Error message"
              }
            },
            "required": [
              "code",
              "message"
            ]
          }
        },
        "required": [
          "jsonrpc",
          "error"
        ]
      }
    },
    "parameters": {},
    "responses": {
      "OkResponse": {
        "description": "Success response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/OkResponse"
            }
          }
        }
      },
      "ErrorMessageResponse": {
        "description": "Success response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorMessageResponse"
            }
          }
        }
      },
      "PrivateGetCancelOnDisconnectResponse": {
        "description": "Success response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PrivateGetCancelOnDisconnectResponse"
            }
          }
        }
      },
      "ErrorResponse": {
        "description": "Error response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      }
    }
  }
}