{
  "openapi": "3.0.0",
  "info": {
    "title": "Deribit API - Supporting",
    "version": "2.1.1",
    "description": "Deribit API specification for Supporting endpoints"
  },
  "servers": [
    {
      "url": "http://localhost:8082/api/v2",
      "description": "local test server"
    },
    {
      "url": "https://test.deribit.com/api/v2"
    }
  ],
  "tags": [
    {
      "name": "Supporting"
    }
  ],
  "paths": {
    "/public/hello": {
      "get": {
        "parameters": [
          {
            "name": "client_name",
            "description": "Client software name",
            "in": "query",
            "schema": {
              "type": "string",
              "example": "My Trading Software"
            },
            "required": true
          },
          {
            "name": "client_version",
            "description": "Client software version",
            "in": "query",
            "schema": {
              "type": "string",
              "example": "1.0.2"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/PublicTestResponse",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "description": "Response example",
                    "value": {
                      "jsonrpc": "2.0",
                      "id": 2841,
                      "result": {
                        "version": "1.2.26"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Method used to introduce the client software connected to Deribit platform over websocket. Provided data may have an impact on the maintained connection and will be collected for internal statistical purposes. In response, Deribit will also introduce itself.",
        "tags": [
          "Supporting",
          "Public",
          "WebSocket Only"
        ],
        "requestBody": {
          "description": "JSON-RPC request body",
          "content": {
            "application/json": {
              "examples": {
                "request": {
                  "description": "JSON-RPC Request Example",
                  "value": {
                    "jsonrpc": "2.0",
                    "id": 2841,
                    "method": "public/hello",
                    "params": {
                      "client_name": "My Trading Software",
                      "client_version": "1.0.2"
                    }
                  }
                }
              }
            }
          }
        },
        "x-mint": {
          "metadata": {
            "title": "public/hello",
            "og:title": "public/hello"
          },
          "href": "/api-reference/supporting/public-hello"
        }
      }
    },
    "/public/status": {
      "get": {
        "parameters": [],
        "responses": {
          "200": {
            "$ref": "#/components/responses/PublicStatusResponse",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "description": "Response example",
                    "value": {
                      "jsonrpc": "2.0",
                      "id": 55,
                      "result": {
                        "locked_currencies": [
                          "BTC",
                          "ETH"
                        ],
                        "locked": true
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Method used to get information about locked currencies",
        "tags": [
          "Supporting",
          "Public"
        ],
        "requestBody": {
          "description": "JSON-RPC request body",
          "content": {
            "application/json": {
              "examples": {
                "request": {
                  "description": "JSON-RPC Request Example",
                  "value": {
                    "jsonrpc": "2.0",
                    "id": 55,
                    "method": "public/status",
                    "params": {}
                  }
                }
              }
            }
          }
        },
        "x-mint": {
          "metadata": {
            "title": "public/status",
            "og:title": "public/status"
          },
          "href": "/api-reference/supporting/public-status"
        }
      }
    },
    "/public/test": {
      "get": {
        "parameters": [
          {
            "description": "The value \"exception\" will trigger an error response. This may be useful for testing wrapper libraries.",
            "in": "query",
            "name": "expected_result",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "exception"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/PublicTestResponse",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "description": "Response example",
                    "value": {
                      "jsonrpc": "2.0",
                      "id": 8212,
                      "result": {
                        "version": "1.2.26"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Tests the connection to the API server, and returns its version. You can use this to make sure the API is reachable, and matches the expected version.",
        "tags": [
          "Supporting",
          "Public"
        ],
        "requestBody": {
          "description": "JSON-RPC request body",
          "content": {
            "application/json": {
              "examples": {
                "request": {
                  "description": "JSON-RPC Request Example",
                  "value": {
                    "jsonrpc": "2.0",
                    "id": 8212,
                    "method": "public/test",
                    "params": {}
                  }
                }
              }
            }
          }
        },
        "x-mint": {
          "metadata": {
            "title": "public/test",
            "og:title": "public/test"
          },
          "href": "/api-reference/supporting/public-test"
        }
      }
    },
    "/public/get_time": {
      "get": {
        "parameters": [],
        "responses": {
          "200": {
            "$ref": "#/components/responses/PublicGetTimeResponse",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "description": "Response example",
                    "value": {
                      "jsonrpc": "2.0",
                      "id": 7365,
                      "result": 1550147385946
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Retrieves the current time (in milliseconds). This API endpoint can be used to check the clock skew between your software and Deribit's systems.",
        "tags": [
          "Supporting",
          "Public"
        ],
        "requestBody": {
          "description": "JSON-RPC request body",
          "content": {
            "application/json": {
              "examples": {
                "request": {
                  "description": "JSON-RPC Request Example",
                  "value": {
                    "jsonrpc": "2.0",
                    "id": 7365,
                    "method": "public/get_time",
                    "params": {}
                  }
                }
              }
            }
          }
        },
        "x-mint": {
          "metadata": {
            "title": "public/get_time",
            "og:title": "public/get_time"
          },
          "href": "/api-reference/supporting/public-get_time"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PublicGetTimeResponse": {
        "properties": {
          "jsonrpc": {
            "description": "The JSON-RPC version (2.0)",
            "enum": [
              "2.0"
            ],
            "type": "string"
          },
          "id": {
            "description": "The id that was sent in the request",
            "type": "integer"
          },
          "result": {
            "description": "Current timestamp (milliseconds since the UNIX epoch)",
            "example": 1517329113791,
            "type": "integer"
          }
        },
        "required": [
          "result",
          "jsonrpc"
        ],
        "type": "object"
      },
      "PublicTestResponse": {
        "properties": {
          "jsonrpc": {
            "description": "The JSON-RPC version (2.0)",
            "enum": [
              "2.0"
            ],
            "type": "string"
          },
          "id": {
            "description": "The id that was sent in the request",
            "type": "integer"
          },
          "result": {
            "properties": {
              "version": {
                "description": "The API version",
                "example": "2.1.26",
                "type": "string"
              }
            },
            "required": [
              "version"
            ],
            "type": "object"
          }
        },
        "required": [
          "result",
          "jsonrpc"
        ],
        "type": "object"
      },
      "PublicStatusResponse": {
        "properties": {
          "jsonrpc": {
            "description": "The JSON-RPC version (2.0)",
            "enum": [
              "2.0"
            ],
            "type": "string"
          },
          "id": {
            "description": "The id that was sent in the request",
            "type": "integer"
          },
          "result": {
            "properties": {
              "locked": {
                "description": "`true` when platform is locked in all currencies, `partial` when some currencies are locked, `false` - when there are not currencies locked",
                "type": "string"
              },
              "locked_indices": {
                "description": "List of currency indices locked platform-wise",
                "type": "array"
              }
            },
            "required": [
              "locked"
            ],
            "type": "object"
          }
        },
        "required": [
          "result",
          "jsonrpc"
        ],
        "type": "object"
      },
      "ErrorResponse": {
        "type": "object",
        "description": "Generic error response for broken references",
        "properties": {
          "jsonrpc": {
            "type": "string",
            "enum": [
              "2.0"
            ]
          },
          "error": {
            "type": "object",
            "properties": {
              "code": {
                "type": "integer",
                "description": "Error code"
              },
              "message": {
                "type": "string",
                "description": "Error message"
              }
            },
            "required": [
              "code",
              "message"
            ]
          }
        },
        "required": [
          "jsonrpc",
          "error"
        ]
      },
      "OkResponse": {
        "properties": {
          "jsonrpc": {
            "description": "The JSON-RPC version (2.0)",
            "enum": [
              "2.0"
            ],
            "type": "string"
          },
          "id": {
            "description": "The id that was sent in the request",
            "type": "integer"
          },
          "result": {
            "description": "Result of method execution. `ok` in case of success",
            "enum": [
              "ok"
            ],
            "type": "string"
          }
        },
        "required": [
          "result",
          "jsonrpc"
        ],
        "type": "object"
      }
    },
    "parameters": {},
    "responses": {
      "PublicStatusResponse": {
        "description": "Success response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PublicStatusResponse"
            }
          }
        }
      },
      "PublicTestResponse": {
        "description": "Success response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PublicTestResponse"
            }
          }
        }
      },
      "PublicGetTimeResponse": {
        "description": "Success response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PublicGetTimeResponse"
            }
          }
        }
      },
      "ErrorResponse": {
        "description": "Error response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "OkResponse": {
        "description": "Success response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/OkResponse"
            }
          }
        }
      }
    }
  }
}